### ISSUE TITLE
OpenZeppelin changes in paths

### ISSUE THREAD

**Issue by ghost** [Cyfrin/foundry-defi-stablecoin-cu#75]
Change the import paths

**Comment by cromewar** [comment]
Hello @preslavsec, can you be more specific on this issue, please?

Also, consider sending a PR if you think changes must be made to the repo.

**Comment by AndroKasrashvili** [comment]
Mock path is updated in current version of openzeppelin, also in an updated version of ERC20Mock constructor does not receive any parameter.

to resolve the issue in HelperConfig use following import:
```solidity
import {ERC20Mock} from "@openzeppelin/contracts/mocks/token/ERC20Mock.sol";
```

**Comment by cromewar** [comment]
Can you send us a PR with these changes? I will make sure the changes are merged.

**Comment by AndroKasrashvili** [comment]
Sure thing, will do on Monday.

**Comment by cromewar** [comment]
Thanks ser will be waiting for the PR :D

**Comment by AndroKasrashvili** [comment]
here you go buddy :) @cromewar 
https://github.com/Cyfrin/foundry-defi-stablecoin-f23/pull/76

**Comment by preslavsec** [comment]
ReentrancyGuard is in openzeppelin/contracts/utils

**Comment by AndroKasrashvili** [comment]
that's correct, please check pr #76

**Comment by cromewar** [comment]
@AndroKasrashvili I haven't merged this PR because, as you are using a newer version of Openzeppelin, there is a mismatch between the version you are using and the version existing on the MAKEFILE. Can you change the version on the MAKEFILE? That way I can merge the PR Right away.

**Comment by PatrickAlphaC** [comment]
I'm pushing a big update soon, stay tuned.
