### ISSUE TITLE
ReentrancyGuard change location 

### ISSUE THREAD

**Issue by BLTC-520** [Cyfrin/foundry-defi-stablecoin-cu#87]
OpenZeppelin's (openzeppelin-contracts) change the security files into the "utils" folder, so for the Lesson12's contracts 

```Solidity
import {ReentrancyGuard} from "@openzeppelin/contracts/security/ReentrancyGuard.sol";

should change to 

import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
```

then you can successfully import the ReentrancyGuard.

**Comment by BLTC-520** [comment]
I saw ppl have pointed out this issue before. Case closed.

**Comment by EngrPips** [comment]
> I saw ppl have pointed out this issue before. Case closed. 

Thanks for the heads-up  anyways.
