### ISSUE TITLE
AggregatorV3Interfacer is error？

### ISSUE THREAD

**Issue by wzl521** [Cyfrin/foundry-defi-stablecoin-cu#94]
I followed the video for installation, but an error occurs when importing, indicating that the file cannot be found。The error is follows：
“
/Users/wzl/workspace/solidity_workspace/foundry-f23/foundry-markdao/lib/chainlink-brownie-contracts/contracts/src/src/v0.8/interfaces/AggregatorV3Interface.sol": No such file or directory (os error 2); check configured remappings
”

**Comment by panditdhamdhere** [comment]
can you please show some error screenshot foundry.toml screenshot and import screen shot

**Comment by panditdhamdhere** [comment]
If you successfully installed make sure you're importing correctly 
Like this 
`import {AggregatorV3Interface} from "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol";`

Also in your foundry.toml check your remappings:
```
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
]
```

I hope it's helpful let me know if you still facing problem

**Comment by EngrPips** [comment]
Hello @wzl521, Did you resolve this issue already? I would like to inform you that the `Discussion` tab is more appropriate for stuff like this.

**Comment by cromewar** [comment]
@wzl521, please let us know if this was solved.

**Comment by cromewar** [comment]
We are closing this due to a lack of follow-up.
